// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/video.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoService_TranscodeVideo_FullMethodName = "/video.VideoService/TranscodeVideo"
	VideoService_WatchJob_FullMethodName       = "/video.VideoService/WatchJob"
	VideoService_ListJobs_FullMethodName       = "/video.VideoService/ListJobs"
	VideoService_GetHLSManifest_FullMethodName = "/video.VideoService/GetHLSManifest"
	VideoService_InspectVideo_FullMethodName   = "/video.VideoService/InspectVideo"
	VideoService_DeleteVideo_FullMethodName    = "/video.VideoService/DeleteVideo"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	// Start HLS transcoding — returns immediately, runs in background.
	TranscodeVideo(ctx context.Context, in *TranscodeVideoRequest, opts ...grpc.CallOption) (*TranscodeVideoResponse, error)
	// Server-streaming: real-time progress until job finishes or client disconnects.
	WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatusResponse], error)
	// Paginated list of cached jobs with optional status filter.
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Get direct public URL for the HLS master playlist (no expiry).
	GetHLSManifest(ctx context.Context, in *GetHLSManifestRequest, opts ...grpc.CallOption) (*GetHLSManifestResponse, error)
	// Scan MinIO and return a full report of what exists for a video_id.
	InspectVideo(ctx context.Context, in *InspectVideoRequest, opts ...grpc.CallOption) (*InspectVideoResponse, error)
	// Delete video and all related files from MinIO + job from Redis.
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) TranscodeVideo(ctx context.Context, in *TranscodeVideoRequest, opts ...grpc.CallOption) (*TranscodeVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscodeVideoResponse)
	err := c.cc.Invoke(ctx, VideoService_TranscodeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoService_ServiceDesc.Streams[0], VideoService_WatchJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobRequest, JobStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoService_WatchJobClient = grpc.ServerStreamingClient[JobStatusResponse]

func (c *videoServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, VideoService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetHLSManifest(ctx context.Context, in *GetHLSManifestRequest, opts ...grpc.CallOption) (*GetHLSManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHLSManifestResponse)
	err := c.cc.Invoke(ctx, VideoService_GetHLSManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) InspectVideo(ctx context.Context, in *InspectVideoRequest, opts ...grpc.CallOption) (*InspectVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectVideoResponse)
	err := c.cc.Invoke(ctx, VideoService_InspectVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVideoResponse)
	err := c.cc.Invoke(ctx, VideoService_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility.
type VideoServiceServer interface {
	// Start HLS transcoding — returns immediately, runs in background.
	TranscodeVideo(context.Context, *TranscodeVideoRequest) (*TranscodeVideoResponse, error)
	// Server-streaming: real-time progress until job finishes or client disconnects.
	WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobStatusResponse]) error
	// Paginated list of cached jobs with optional status filter.
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Get direct public URL for the HLS master playlist (no expiry).
	GetHLSManifest(context.Context, *GetHLSManifestRequest) (*GetHLSManifestResponse, error)
	// Scan MinIO and return a full report of what exists for a video_id.
	InspectVideo(context.Context, *InspectVideoRequest) (*InspectVideoResponse, error)
	// Delete video and all related files from MinIO + job from Redis.
	DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServiceServer struct{}

func (UnimplementedVideoServiceServer) TranscodeVideo(context.Context, *TranscodeVideoRequest) (*TranscodeVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscodeVideo not implemented")
}
func (UnimplementedVideoServiceServer) WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchJob not implemented")
}
func (UnimplementedVideoServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedVideoServiceServer) GetHLSManifest(context.Context, *GetHLSManifestRequest) (*GetHLSManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHLSManifest not implemented")
}
func (UnimplementedVideoServiceServer) InspectVideo(context.Context, *InspectVideoRequest) (*InspectVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectVideo not implemented")
}
func (UnimplementedVideoServiceServer) DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}
func (UnimplementedVideoServiceServer) testEmbeddedByValue()                      {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_TranscodeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscodeVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).TranscodeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_TranscodeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).TranscodeVideo(ctx, req.(*TranscodeVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_WatchJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoServiceServer).WatchJob(m, &grpc.GenericServerStream[WatchJobRequest, JobStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoService_WatchJobServer = grpc.ServerStreamingServer[JobStatusResponse]

func _VideoService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetHLSManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHLSManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetHLSManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetHLSManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetHLSManifest(ctx, req.(*GetHLSManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_InspectVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).InspectVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_InspectVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).InspectVideo(ctx, req.(*InspectVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteVideo(ctx, req.(*DeleteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranscodeVideo",
			Handler:    _VideoService_TranscodeVideo_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _VideoService_ListJobs_Handler,
		},
		{
			MethodName: "GetHLSManifest",
			Handler:    _VideoService_GetHLSManifest_Handler,
		},
		{
			MethodName: "InspectVideo",
			Handler:    _VideoService_InspectVideo_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _VideoService_DeleteVideo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchJob",
			Handler:       _VideoService_WatchJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/video.proto",
}
