// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/video.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resolution int32

const (
	Resolution_RESOLUTION_UNKNOWN Resolution = 0
	Resolution_RESOLUTION_360P    Resolution = 1
	Resolution_RESOLUTION_480P    Resolution = 2
	Resolution_RESOLUTION_720P    Resolution = 3
	Resolution_RESOLUTION_1080P   Resolution = 4
	Resolution_RESOLUTION_1440P   Resolution = 5
	Resolution_RESOLUTION_4K      Resolution = 6
)

// Enum value maps for Resolution.
var (
	Resolution_name = map[int32]string{
		0: "RESOLUTION_UNKNOWN",
		1: "RESOLUTION_360P",
		2: "RESOLUTION_480P",
		3: "RESOLUTION_720P",
		4: "RESOLUTION_1080P",
		5: "RESOLUTION_1440P",
		6: "RESOLUTION_4K",
	}
	Resolution_value = map[string]int32{
		"RESOLUTION_UNKNOWN": 0,
		"RESOLUTION_360P":    1,
		"RESOLUTION_480P":    2,
		"RESOLUTION_720P":    3,
		"RESOLUTION_1080P":   4,
		"RESOLUTION_1440P":   5,
		"RESOLUTION_4K":      6,
	}
)

func (x Resolution) Enum() *Resolution {
	p := new(Resolution)
	*p = x
	return p
}

func (x Resolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resolution) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_video_proto_enumTypes[0].Descriptor()
}

func (Resolution) Type() protoreflect.EnumType {
	return &file_proto_video_proto_enumTypes[0]
}

func (x Resolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resolution.Descriptor instead.
func (Resolution) EnumDescriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNKNOWN    JobStatus = 0
	JobStatus_JOB_STATUS_PENDING    JobStatus = 1
	JobStatus_JOB_STATUS_PROCESSING JobStatus = 2
	JobStatus_JOB_STATUS_DONE       JobStatus = 3
	JobStatus_JOB_STATUS_FAILED     JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_PROCESSING",
		3: "JOB_STATUS_DONE",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":    0,
		"JOB_STATUS_PENDING":    1,
		"JOB_STATUS_PROCESSING": 2,
		"JOB_STATUS_DONE":       3,
		"JOB_STATUS_FAILED":     4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_video_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_video_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{1}
}

type TranscodeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                        // Video ID in MinIO
	OriginalPath  string                 `protobuf:"bytes,2,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`         // Path in MinIO: videos/{id}.mp4
	Resolutions   []Resolution           `protobuf:"varint,3,rep,packed,name=resolutions,proto3,enum=video.Resolution" json:"resolutions,omitempty"` // Desired resolutions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeVideoRequest) Reset() {
	*x = TranscodeVideoRequest{}
	mi := &file_proto_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeVideoRequest) ProtoMessage() {}

func (x *TranscodeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeVideoRequest.ProtoReflect.Descriptor instead.
func (*TranscodeVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *TranscodeVideoRequest) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *TranscodeVideoRequest) GetResolutions() []Resolution {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type TranscodeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeVideoResponse) Reset() {
	*x = TranscodeVideoResponse{}
	mi := &file_proto_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeVideoResponse) ProtoMessage() {}

func (x *TranscodeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeVideoResponse.ProtoReflect.Descriptor instead.
func (*TranscodeVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeVideoResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TranscodeVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{2}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ResolutionProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    Resolution             `protobuf:"varint,1,opt,name=resolution,proto3,enum=video.Resolution" json:"resolution,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=video.JobStatus" json:"status,omitempty"`
	LastSegment   int32                  `protobuf:"varint,3,opt,name=last_segment,json=lastSegment,proto3" json:"last_segment,omitempty"`       // Last processed segment
	TotalSegments int32                  `protobuf:"varint,4,opt,name=total_segments,json=totalSegments,proto3" json:"total_segments,omitempty"` // Total expected segments
	ThumbnailDone bool                   `protobuf:"varint,5,opt,name=thumbnail_done,json=thumbnailDone,proto3" json:"thumbnail_done,omitempty"` // Whether thumbnail was generated
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionProgress) Reset() {
	*x = ResolutionProgress{}
	mi := &file_proto_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionProgress) ProtoMessage() {}

func (x *ResolutionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionProgress.ProtoReflect.Descriptor instead.
func (*ResolutionProgress) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{3}
}

func (x *ResolutionProgress) GetResolution() Resolution {
	if x != nil {
		return x.Resolution
	}
	return Resolution_RESOLUTION_UNKNOWN
}

func (x *ResolutionProgress) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *ResolutionProgress) GetLastSegment() int32 {
	if x != nil {
		return x.LastSegment
	}
	return 0
}

func (x *ResolutionProgress) GetTotalSegments() int32 {
	if x != nil {
		return x.TotalSegments
	}
	return 0
}

func (x *ResolutionProgress) GetThumbnailDone() bool {
	if x != nil {
		return x.ThumbnailDone
	}
	return false
}

func (x *ResolutionProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VideoId         string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Status          JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=video.JobStatus" json:"status,omitempty"`
	Progress        []*ResolutionProgress  `protobuf:"bytes,4,rep,name=progress,proto3" json:"progress,omitempty"`
	OriginalWidth   int32                  `protobuf:"varint,5,opt,name=original_width,json=originalWidth,proto3" json:"original_width,omitempty"`
	OriginalHeight  int32                  `protobuf:"varint,6,opt,name=original_height,json=originalHeight,proto3" json:"original_height,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *JobStatusResponse) GetProgress() []*ResolutionProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *JobStatusResponse) GetOriginalWidth() int32 {
	if x != nil {
		return x.OriginalWidth
	}
	return 0
}

func (x *JobStatusResponse) GetOriginalHeight() int32 {
	if x != nil {
		return x.OriginalHeight
	}
	return 0
}

func (x *JobStatusResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type GetHLSManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds, default 3600
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHLSManifestRequest) Reset() {
	*x = GetHLSManifestRequest{}
	mi := &file_proto_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHLSManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHLSManifestRequest) ProtoMessage() {}

func (x *GetHLSManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHLSManifestRequest.ProtoReflect.Descriptor instead.
func (*GetHLSManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetHLSManifestRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetHLSManifestRequest) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GetHLSManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHLSManifestResponse) Reset() {
	*x = GetHLSManifestResponse{}
	mi := &file_proto_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHLSManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHLSManifestResponse) ProtoMessage() {}

func (x *GetHLSManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHLSManifestResponse.ProtoReflect.Descriptor instead.
func (*GetHLSManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetHLSManifestResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetHLSManifestResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_proto_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_proto_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_video_proto protoreflect.FileDescriptor

const file_proto_video_proto_rawDesc = "" +
	"\n" +
	"\x11proto/video.proto\x12\x05video\"\x8c\x01\n" +
	"\x15TranscodeVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12#\n" +
	"\roriginal_path\x18\x02 \x01(\tR\foriginalPath\x123\n" +
	"\vresolutions\x18\x03 \x03(\x0e2\x11.video.ResolutionR\vresolutions\"J\n" +
	"\x16TranscodeVideoResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xf8\x01\n" +
	"\x12ResolutionProgress\x121\n" +
	"\n" +
	"resolution\x18\x01 \x01(\x0e2\x11.video.ResolutionR\n" +
	"resolution\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.video.JobStatusR\x06status\x12!\n" +
	"\flast_segment\x18\x03 \x01(\x05R\vlastSegment\x12%\n" +
	"\x0etotal_segments\x18\x04 \x01(\x05R\rtotalSegments\x12%\n" +
	"\x0ethumbnail_done\x18\x05 \x01(\bR\rthumbnailDone\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xa1\x02\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.video.JobStatusR\x06status\x125\n" +
	"\bprogress\x18\x04 \x03(\v2\x19.video.ResolutionProgressR\bprogress\x12%\n" +
	"\x0eoriginal_width\x18\x05 \x01(\x05R\roriginalWidth\x12'\n" +
	"\x0foriginal_height\x18\x06 \x01(\x05R\x0eoriginalHeight\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x01R\x0fdurationSeconds\"Q\n" +
	"\x15GetHLSManifestRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\"I\n" +
	"\x16GetHLSManifestResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\"/\n" +
	"\x12DeleteVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"I\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xa2\x01\n" +
	"\n" +
	"Resolution\x12\x16\n" +
	"\x12RESOLUTION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fRESOLUTION_360P\x10\x01\x12\x13\n" +
	"\x0fRESOLUTION_480P\x10\x02\x12\x13\n" +
	"\x0fRESOLUTION_720P\x10\x03\x12\x14\n" +
	"\x10RESOLUTION_1080P\x10\x04\x12\x14\n" +
	"\x10RESOLUTION_1440P\x10\x05\x12\x11\n" +
	"\rRESOLUTION_4K\x10\x06*\x82\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15JOB_STATUS_PROCESSING\x10\x02\x12\x13\n" +
	"\x0fJOB_STATUS_DONE\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xb5\x02\n" +
	"\fVideoService\x12M\n" +
	"\x0eTranscodeVideo\x12\x1c.video.TranscodeVideoRequest\x1a\x1d.video.TranscodeVideoResponse\x12A\n" +
	"\fGetJobStatus\x12\x17.video.JobStatusRequest\x1a\x18.video.JobStatusResponse\x12M\n" +
	"\x0eGetHLSManifest\x12\x1c.video.GetHLSManifestRequest\x1a\x1d.video.GetHLSManifestResponse\x12D\n" +
	"\vDeleteVideo\x12\x19.video.DeleteVideoRequest\x1a\x1a.video.DeleteVideoResponseB<Z:github.com/devlucas-java/luca-s3/internal/delivery/grpc/pbb\x06proto3"

var (
	file_proto_video_proto_rawDescOnce sync.Once
	file_proto_video_proto_rawDescData []byte
)

func file_proto_video_proto_rawDescGZIP() []byte {
	file_proto_video_proto_rawDescOnce.Do(func() {
		file_proto_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)))
	})
	return file_proto_video_proto_rawDescData
}

var file_proto_video_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_video_proto_goTypes = []any{
	(Resolution)(0),                // 0: video.Resolution
	(JobStatus)(0),                 // 1: video.JobStatus
	(*TranscodeVideoRequest)(nil),  // 2: video.TranscodeVideoRequest
	(*TranscodeVideoResponse)(nil), // 3: video.TranscodeVideoResponse
	(*JobStatusRequest)(nil),       // 4: video.JobStatusRequest
	(*ResolutionProgress)(nil),     // 5: video.ResolutionProgress
	(*JobStatusResponse)(nil),      // 6: video.JobStatusResponse
	(*GetHLSManifestRequest)(nil),  // 7: video.GetHLSManifestRequest
	(*GetHLSManifestResponse)(nil), // 8: video.GetHLSManifestResponse
	(*DeleteVideoRequest)(nil),     // 9: video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),    // 10: video.DeleteVideoResponse
}
var file_proto_video_proto_depIdxs = []int32{
	0,  // 0: video.TranscodeVideoRequest.resolutions:type_name -> video.Resolution
	0,  // 1: video.ResolutionProgress.resolution:type_name -> video.Resolution
	1,  // 2: video.ResolutionProgress.status:type_name -> video.JobStatus
	1,  // 3: video.JobStatusResponse.status:type_name -> video.JobStatus
	5,  // 4: video.JobStatusResponse.progress:type_name -> video.ResolutionProgress
	2,  // 5: video.VideoService.TranscodeVideo:input_type -> video.TranscodeVideoRequest
	4,  // 6: video.VideoService.GetJobStatus:input_type -> video.JobStatusRequest
	7,  // 7: video.VideoService.GetHLSManifest:input_type -> video.GetHLSManifestRequest
	9,  // 8: video.VideoService.DeleteVideo:input_type -> video.DeleteVideoRequest
	3,  // 9: video.VideoService.TranscodeVideo:output_type -> video.TranscodeVideoResponse
	6,  // 10: video.VideoService.GetJobStatus:output_type -> video.JobStatusResponse
	8,  // 11: video.VideoService.GetHLSManifest:output_type -> video.GetHLSManifestResponse
	10, // 12: video.VideoService.DeleteVideo:output_type -> video.DeleteVideoResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_video_proto_init() }
func file_proto_video_proto_init() {
	if File_proto_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_proto_goTypes,
		DependencyIndexes: file_proto_video_proto_depIdxs,
		EnumInfos:         file_proto_video_proto_enumTypes,
		MessageInfos:      file_proto_video_proto_msgTypes,
	}.Build()
	File_proto_video_proto = out.File
	file_proto_video_proto_goTypes = nil
	file_proto_video_proto_depIdxs = nil
}
